FROM golang:alpine AS builder

ENV PATH /go/bin:/usr/local/go/bin:$PATH
ENV GOPATH /go

RUN apk --no-cache add \
	                                  

LABEL "maintainer Greg Sharpe (docker+me@gregsharpe.co.uk)"


